ocicuc: Add pthread to LIBS to fix build with GCC 5.1
Build with GCC 5.1 failed with error:
[  238s] g++ -o out/tizen/x86/release/resource/examples/ocicuc/monoprocess -s -m32 out/tizen/x86/release/resource/examples/ocicuc/monoprocess.o out/tizen/x86/release/resource/examples/ocicuc/driver.o out/tizen/x86/release/resource/examples/ocicuc/utility.o out/tizen/x86/release/resource/examples/ocicuc/light_resource.o -Lout/tizen/x86/release -L. -loc -loctbstack -lcoap -loc_logger -lboost_program_options
[  238s] /usr/lib/gcc/i586-tizen-linux/5.1/../../../../i586-tizen-linux/bin/ld: out/tizen/x86/release/resource/examples/ocicuc/monoprocess.o: undefined reference to symbol 'pthread_create@@GLIBC_2.1'
[  238s] /lib/libpthread.so.0: error adding symbols: DSO missing from command line
[  238s] collect2: error: ld returned 1 exit status

Adding pthread to LIBS fixes the issue